name: GitHub Pages

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Get branch name (push)
        if: github.event_name != 'pull_request'
        run: echo "BRANCH_NAME=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

      - name: Get branch name (pull request)
        if: github.event_name == 'pull_request'
        run: echo "BRANCH_NAME=${GITHUB_HEAD_REF}" >> $GITHUB_ENV

      - run: yarn install --frozen-lockfile
      - run: yarn build
        env:
          PUBLIC_URL: /store/${{ env.BRANCH_NAME }}/app
      - run: yarn build:storybook

      - name: Deploy app
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          destination_dir: ${{ env.BRANCH_NAME }}/app

      - name: Deploy storybook
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./storybook-static
          destination_dir: ${{ env.BRANCH_NAME }}/storybook

      - uses: marocchino/sticky-pull-request-comment@v2
        if: github.event_name == 'pull_request' && success()
        with:
          message: |
            [💅 Storybook](https://metaplex.github.io/store/${{ env.BRANCH_NAME }}/storybook/)
            [🚀 App](https://metaplex.github.io/store/${{ env.BRANCH_NAME }}/app/)
